This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./Bao_cao_TLKH.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Bao_cao_TLKH.acn....done (20 entries accepted, 0 rejected).
Sorting entries....done (95 comparisons).
Generating output file Bao_cao_TLKH.acr....done (29 lines written, 0 warnings).
Output written in Bao_cao_TLKH.acr.
Transcript written in Bao_cao_TLKH.alg.
